project:
  type: website

website:
  title: "Noj"
  favicon: "Noj.svg"
  navbar:
    background: white
    logo: "Noj.svg"
    logo-alt: "Noj"
    logo-href: "/"
    left:
      - text: "Quick Start"
        menu:
          - text: "Learning resources"
            href: quick_start/learning_resources.qmd
      - text: "Learn Data Science"
        menu:
          - text: "What is data science?"
            href: learn/index.qmd
          - text: "Import"
            href: learn/import.qmd
          - text: "Wrangle"
            href: learn/wrangle/wrangle.qmd
          - text: "Visualize"
            href: learn/visualize.qmd
          - text: "Statistical Modeling"
            href: learn/stat/stat_index.qmd
          - text: "Machine Learning"
            href: learn/ml/machine_index.qmd
          - text: "Evaluate"
            href: learn/evaluate.qmd
          - text: "Communicate"
            href: learn/communicate.qmd
      - text: "Reference"
        menu:
          - text: "clay"
            href: ref/clay.qmd
          - text: "kindly"
            href: ref/kindly.qmd
          - text: "plotje"
            href: ref/plotje.qmd
          - text: "tech.ml.dataset"
            href: ref/tech_ml_dataset.qmd
          - text: "ham-fisted"
            href: ref/ham_fisted.qmd
          - text: "dtype-next"
            href: ref/dtype_next.qmd
          - text: "tablecloth"
            href: ref/tablecloth.qmd
          - text: "tech.parquet"
            href: ref/tech_parquet.qmd
          - text: "clojure.java-time"
            href: ref/clojure_java_time.qmd
          - text: "fastmath"
            href: ref/fastmath.qmd
          - text: "fitdistr"
            href: ref/fitdistr.qmd
          - text: "same-ish"
            href: ref/same_ish.qmd
          - text: "metamorph.ml"
            href: ref/metamorph_ml.qmd
          - text: "scicloj.ml.tribuo"
            href: ref/scicloj_ml_tribuo.qmd
          - text: "sklearn-clj"
            href: ref/sklearn_clj.qmd
          - text: "clojisr"
            href: ref/clojisr.qmd
          - text: "libpython-clj"
            href: ref/libpython_clj.qmd
          - text: "kind-pyplot"
            href: ref/kind_pyplot.qmd
      - text: "Other Materials"
        menu:
          - text: "Other recommended libraries"
            href: other_materials/other_libraries.qmd
          - text: "Chicago bike times"
            href: other_materials/chicago_bike_times.qmd
          - text: "tableplot"
            href: other_materials/tableplot.qmd
          - text: "plotly"
            href: other_materials/plotly.qmd
          - text: "hanami"
            href: other_materials/hanami.qmd
          - text: "echarts"
            href: other_materials/echarts.qmd
    right:
       - icon: github
         href: "https://github.com/scicloj/noj"
         aria-label: "Noj on GitHub"
      
  sidebar:
    - id: qs
      style: "docked"
      search: true
      contents:
      - text: "Learning resources"
        href: quick_start/learning_resources.qmd
    - id: learn 
      style: "docked"
      search: true
      contents:
      - text: "What is data science?"
        href: learn/index.qmd
      - text: "Import"
        href: learn/import.qmd
      - part: learn/wrangle/wrangle.qmd
        chapters:
          - text: "Table processing"
            href: learn/wrangle/table_processing.qmd
          - text: "Advanced table processing"
            href: learn/wrangle/advanced_table_processing.qmd
      - text: "Visualize"
        href: learn/visualize.qmd
      - part: learn/stat/stat_index.qmd
        chapters:
          - text: "Single variable distribution"
            href: learn/stat/single_variable_distribution.qmd
      - part: learn/ml/ml_basic.qmd
        chapters:
          - text: "Machine learning pipelines"
            href: learn/ml/ml_pipelines.qmd
          - text: "Preprocessing of categorical variables"
            href: learn/ml/prepare_for_ml.qmd
          - text: "AutoML using metamorph pipelines"
            href: learn/ml/automl.qmd
          - text: "Ordinary least squares with interactions"
            href: learn/ml/interactions_ols.qmd
      - text: "Evaluate"
        href: learn/evaluate.qmd
      - text: "Communicate"
        href: learn/communicate.qmd
    - id: ref
      style: "docked"
      search: true
      contents:
      - text: "clay"
        href: ref/clay.qmd
      - text: "kindly"
        href: ref/kindly.qmd
      - text: "plotje"
        href: ref/plotje.qmd
      - text: "tech.ml.dataset"
        href: ref/tech_ml_dataset.qmd
      - text: "ham-fisted"
        href: ref/ham_fisted.qmd
      - text: "dtype-next"
        href: ref/dtype_next.qmd
      - text: "tablecloth"
        href: ref/tablecloth.qmd
      - text: "tech.parquet"
        href: ref/tech_parquet.qmd
      - text: "clojure.java-time"
        href: ref/clojure_java_time.qmd
      - text: "fastmath"
        href: ref/fastmath.qmd
      - text: "fitdistr"
        href: ref/fitdistr.qmd
      - text: "same-ish"
        href: ref/same_ish.qmd
      - part: metamorph_ml.qmd
        chapters:
          - text: "Smile classification models reference"
            href: ref/metamorph/smile_classification.qmd
          - text: "Smile regression models reference"
            href: ref/metamorph/smile_regression.qmd
          - text: "Smile other models reference"
            href: ref/metamorph/smile_others.qmd
          - text: "Xgboost model reference"
            href: ref/metamorph/xgboost.qmd
          - text: "Transformer reference"
            href: ref/metamorph/transformer.qmd           
      - text: "scicloj.ml.tribuo"
        href: ref/scicloj_ml_tribuo.qmd
      - text: "sklearn-clj"
        href: ref/sklearn_clj.qmd
      - text: "clojisr"
        href: ref/clojisr.qmd
      - text: "libpython-clj"
        href: ref/libpython_clj.qmd
      - text: "kind-pyplot"
        href: ref/kind_pyplot.qmd
    - id: other-libs
      style: "docked"
      search: true
      contents:
      - text: "Other libraries"
        href: other_materials/other_libraries.qmd
      - text: "Chicago Bike Times"
        href: other_materials/chicago_bike_times.qmd
      - text: "tableplot"
        href: other_materials/tableplot.qmd
      - text: "plotly"
        href: other_materials/plotly.qmd
      - text: "hanami"
        href: other_materials/hanami.qmd
      - text: "echarts"
        href: other_materials/echarts.qmd      
  page-footer:
    right:
      Built with Clay and Quarto
    center:
      Noj — A Clojure data science toolkit
format:
  html:
    theme: [ cosmo, custom.scss]
    toc: false
      

