project:
  type: website

website:
  title: "Noj"
  navbar:
    background: light
    logo: "Noj.svg"
    logo-alt: "Noj"
    logo-href: "/"   
    right:
      - quick_start_guide.qmd
      - href: learn/index.qmd
        text: "Learn data science"
      - href: ref/index.qmd
        text: "Reference"
      - href: case_studies/index.qmd
        text: "Case studies"
      - community.qmd
      - about.qmd
      - icon: github
        href: "https://github.com/noj"
        aria-label: "Noj on GitHub"
      
  sidebar:
    - id: learn 
      style: "docked"
      search: true
      contents:
      - learn/index.qmd
      - learn/dataset.qmd
    - id: ref
      style: "docked"
      search: true
      contents:
      - ref/index.qmd
    - id: case-studies
      style: "docked"
      search: true
      contents:
      - case_studies/index.qmd
  page-footer:
    center:
      Noj — a data analysis stack for Clojure
format:
  html:
    theme: [ cosmo, custom.scss]
    toc: false
    grid:
      body-width: 1200px    # Maximum width of the main article/content
      

